import { useState } from "react";
import Head from "next/head";
import About from "../components/About";
import Header from "../components/Header";
import Menu from "../components/Menu";
import Services from "../components/Services";
import Footer from "../components/Footer";
import Testimonials from "../components/Testimonials";
// import prisma from '../lib/prisma'
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

export async function getServerSideProps() {
  const categories = await prisma.category_price.findMany({
    include: {
      flavour: true,
    },
  });

  const clientStories = await prisma.client_stories.findMany({
    where: {
      approved: true,
    },
  });
  return {
    props: {
      categories,
      clientStories
    },
  };
}

export default function Home(props) {
  const [categories, setCategories] = useState(props.categories);
  const [clientStories, setClientStories] = useState(props.clientStories)
  return (
    <div className="main">
      <Head>
        <title>Cake Fairy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* <div className="absolute flex justify-center px-2 top-48 xl:top-80">
        <h1 className="sm:p-7 md:w-5/6 text italic">
          "Whether you love the simplicity of a banana or the taste of icing
          we’ve got sweet treats for every craving!"
        </h1>
      </div> */}
      <Services />
      <Menu categories={categories} />
      <About />
      <Testimonials clientStories={clientStories} setClientStories={setClientStories}/>
      <Footer />
    </div>
  );
}
